# Generated by Django 2.2.4 on 2019-08-24 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('food_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('current_price', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('other_charge', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(default='active', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
