# Generated by Django 2.2.4 on 2019-08-24 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=50)),
                ('bill', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('commission', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('remission', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_contact', models.CharField(max_length=250)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_feedback', models.TextField(blank=True)),
                ('customer_rating', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(default='active', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('food_id', models.ManyToManyField(blank=True, related_name='ordered_product', to='food.Table')),
            ],
        ),
    ]
